### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by kevlarr** [kevlarr/mngr#2]
To make the application easily configurable, allow specifying a configuration file to load important details from.

## Static assets

Specify the path to the static assets directory containing the JS and CSS files, which can be freely edited.

```toml
[assets]
static_dir = "/path/to/static"/
```

## Database

```toml
[database]

connection = "conn string"
```

## Database tables

Rather than simply trying to expose all tables in the database, users should be able to explicitly list the accessible tables in the config file, eg. something like...

```toml
[database.tables]

# Basic list of tables
include = [
  "schema1.one-table",
  "schema2.another-table",
  "some-unqualified-table",
  # ... more tables
]

# Glob patterns
include = [
  "schema1.*",
  "schema2.table_prefix_*",
  "schema_prefix_*.*",
]

# Any specify exclusions in conjunction with globs
exclude = [
  "schema1.uneditable_table",
  "schema2.some_prefix_*",
]
```
